title: That (D)Transit Blog
description: Documenting Chicagoâ€™s transit stories.
url: "https://dtransit-main.github.io"
baseurl: "/thatdtransitblog"

theme: null
markdown: kramdown
plugins:
  - jekyll-feed
