title: That (D)Transit Blog
description: A blog about transit and development
baseurl: "" # leave empty if it's username.github.io
url: "https://dtransit-main.github.io/thatdtransitblog" # your GitHub Pages URL
theme: null
