title: That (D)Transit Blog
description: A blog about transit, cities, and design.

url: "https://dtransit-main.github.io"
baseurl: "/thatdtransitblog"

theme: null
markdown: kramdown
plugins:
  - jekyll-feed
